const ADD_APPOINTMENT = 'ADD_APPOINTMENT';
const REMOVE_APPOINTMENT = 'REMOVE_APPOINTMENT';
const ADD_USER = 'ADD_USER';
const REMOVE_USER = 'REMOVE_USER';

export { ADD_APPOINTMENT, REMOVE_APPOINTMENT, ADD_USER, REMOVE_USER };